### ISSUE TITLE
Handling of UTF-8 text encoding

### ISSUE THREAD

**Issue by farzami** [pnlng/pdfoutliner#3]
I tried creating a file with non-English characters (UTF-8 encoding) on Windows 10. The UTF-8 text in the PDFtk bookmarks file (TOC-outline.txt) is rendered correctly. But if I use pdfoutliner for direct generation of the outlined pdf file, the generated outline contains non-readable characters. It seems that the problem arises when PDFtk is called.

According to [PDFtk manual](https://www.pdflabs.com/docs/pdftk-man-page/#dest-op-update-info-utf8), changing the `update_info` option to `update_info_utf8` can solve the problem.

**Comment by pnlng** [comment]
An [earlier PR](https://github.com/pnlng/pdfoutliner/pull/1) has added the flag `--utf8`. I haven't release a new version because I wanted to make some changes to the CLI. For one, making it use UTF-8 by default. 

In the mean time, you can download/clone this repository, run `pip install .` in the directory to install the latest version manually. Adding `--utf8` to your command should solve the issue.
